server:
  port: 9092
  # \u89E3\u51B3\u8BF7\u6C42\u5934\u8FC7\u957F\u7684\u95EE\u9898
  max-http-header-size: 4096000
  tomcat:
    max-http-form-post-size: 500MB  # \u8BBE\u7F6Etomcat\u8BF7\u6C42\u7684\u6700\u5927\u503C
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/xdk_msb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(1ONwa16hpUgmzo4GB9wktg==)
    password: ENC(wzZqDJLp2hGPrk6NZIo62RT7ap1Vw/Hs)
    hikari:
      catalog: xdk_msb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

# \u626B\u63CFmapper\u6587\u4EF6\u6240\u5728\u8DEF\u5F84
mybatis:
  mapper-locations: classpath:mapper/**/mapper-*.xml,classpath:msb/mapper-*.xml

# 控制swagger2是否显示，true显示，false不显示
swagger:
  enable: true

logging:
  file:
    path: ./logs/msb.log


